force-app/main/default/objects/Contact/fields/Most_Recent_Payment__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Payment__c</fullName>
    <label>Most Recent Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000}-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProjectPaymentsController.cls
public with sharing class ProjectPaymentsController {
    @AuraEnabled(Cacheable=true)
    public static List<ContactWrapper> getProjectPayments(Id projectId) {
        // To avoid querying all of the Contacts in the system, collect the list of 
        // Contacts that have made a payment to the Project in preparation for a
        // second query with the structure that we'll send back to the Component
        Set<Id> referencedContactIds = new Set<Id>();
        for(Payment__c payment : [select Id, Contact__c from Payment__c where Project__c = :projectId]){
            referencedContactIds.add(payment.Contact__c);
        }

        // Now query just the Contacts that have made a payment to the Project and wrap them for sending to 
        List<ContactWrapper> wrapperList = new List<ContactWrapper>();
        for(Contact contact : [SELECT Id, Name, Total_Payments__c, Most_Recent_Payment__c, 
                                (select Id, Name, Payment_Amount__c, Payment_Date__c from Payments__r order by Payment_Date__c desc) 
                                from Contact 
                                where Id in :referencedContactIds])
        {
            wrapperList.add(new ContactWrapper(contact));
        }

        return wrapperList;
    }

    public class ContactWrapper {
        @AuraEnabled
        public Contact contactRecord;
        @AuraEnabled
        public List<Payment__c> paymentRecords;

        public ContactWrapper(Contact contactRecord){
            this.contactRecord = contactRecord;
            this.paymentRecords = new List<Payment__c>();
            for(Payment__c payment : contactRecord.Payments__r){
                this.paymentRecords.add(payment);
            }
        }
    }
}