force-app/main/default/objects/Contact/fields/Most_Recent_Payment__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Payment__c</fullName>
    <label>Most Recent Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000}-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContactUtils.cls
public class ContactUtils {
    public static List<Contact> calculatePaymentFields(Set<Id> contactIds){
        Map<Id, Contact> calculatedContacts = new Map<Id, Contact>();
        List<AggregateResult> AggregateContacts = [select Contact__c, Sum(Payment_Amount__c) amount, max(Payment_Date__c) maxDate 
                                                    from Payment__c 
                                                    where Contact__c in :contactIds 
                                                    group by Contact__c];
        for(AggregateResult aggr : AggregateContacts){             
            Contact calcContact = new Contact(); 
            calcContact.Id = (Id)aggr.get('Contact__c'); 
            calcContact.Most_Recent_Payment__c = (Date)aggr.get('maxDate'); 
            calcContact.Total_Payments__c = (decimal)aggr.get('amount');
            calculatedContacts.put(calcContact.Id, calcContact);
        } 

        // For any Contacts that had their last payment deleted they won't 
        // show up in the aggregate results so we need to set their Total_Payments__c to null
        for(Id contactId : contactIds){
            if(!calculatedContacts.keySet().contains(contactId)){
                calculatedContacts.put(contactId, new Contact(Id=contactId, Total_Payments__c=null, Most_Recent_Payment__c = null));
            }
        }
        
        return calculatedContacts.values();
    }
}