force-app/main/default/objects/Contact/fields/Most_Recent_Payment__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Payment__c</fullName>
    <label>Most Recent Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000}-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ContactPaymentsControllerTest.cls
@isTest
public class ContactPaymentsControllerTest {
    private static Contact contact1;
    private static Contact contact2;

    private static Project__c project1;
    private static Project__c project2;

    @isTest
    private static void createUpdateDeletePayments(){
        loadProjects();
        loadContacts();

        Test.startTest();
        Payment__c payment1 = new Payment__c(Project__c = project1.Id, Contact__c = contact1.Id, Payment_Amount__c = 100, Payment_Date__c = Date.today());
        Payment__c payment2 = new Payment__c(Project__c = project1.Id, Contact__c = contact2.Id, Payment_Amount__c = 1000, Payment_Date__c = Date.today());
        
        // Check handling insert
        ContactPaymentsController.savePayments(new List<Payment__c>{payment1, payment2});
        List<Payment__c> checkPayments = [select Id from Payment__c];
        System.assertEquals(2, checkPayments.size());

        // Check handing insert and update
        payment1.Payment_Amount__c = 400;
        Payment__c payment3 = new Payment__c(Project__c = project2.Id, Contact__c = contact2.Id, Payment_Amount__c = 1000, Payment_Date__c = Date.today());
        ContactPaymentsController.savePayments(new List<Payment__c>{payment1, payment3});
        checkPayments = [select Id from Payment__c];
        System.assertEquals(3, checkPayments.size());

        // Check handing delete
        ContactPaymentsController.deletePayment(payment2.Id);
        checkPayments = [select Id from Payment__c];
        System.assertEquals(2, checkPayments.size());

        Test.stopTest();
    }  

    @TestSetup
    static void makeData(){
        contact1 = new Contact(FirstName = 'Test', LastName = 'Person1');
        contact2 = new Contact(FirstName = 'Test', LastName = 'Person2');
        Database.insert(new List<Contact>{contact1, contact2});
    
        project1 = new Project__c(Name = 'Test Project1');
        project2 = new Project__c(Name = 'Test Project2');
        Database.insert(new List<Project__c>{project1, project2});
    }

    // Load Contacts that were created by TestSetup
    private static void loadContacts(){
        // Clearing out static record instances so this method can be re-called 
        // for checking results throughout unit tests
        contact1 = null;
        contact2 = null;
        for(Contact contact : [select Id, FirstName, LastName, Total_Payments__c, Most_Recent_Payment__c from Contact]){
            if(contact.LastName == 'Person1') contact1 = contact;
            else if(contact.LastName == 'Person2') contact2 = contact;
        }
    }
    // Load Projects that were created by TestSetup
    private static void loadProjects(){
        // Clearing out static record instances so this method can be re-called 
        // for checking results throughout unit tests
        project1 = null;
        project2 = null;
        for(Project__c project : [select Id, Name, Total_Payments__c from Project__c]){
            if(project.Name == 'Test Project1') project1 = project;
            else if(project.Name == 'Test Project2') project2 = project;
        }
    }
}