force-app/main/default/objects/Contact/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000}-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProjectPaymentsControllerTest.cls
@isTest
public class ProjectPaymentsControllerTest {
    private static Contact contact1;
    private static Contact contact2;

    private static Project__c project1;
    private static Project__c project2;
    
    private static Payment__c payment11;
    private static Payment__c payment12;
    private static Payment__c payment21;
    private static Payment__c payment22;

    @isTest
    private static void testQuerying(){
        loadProjects();

        Test.startTest();
        List<ProjectPaymentsController.ContactWrapper> queryResults = ProjectPaymentsController.getProjectPayments(project1.Id);

        // Check that the query results contain the number of records we're expecting
        System.assertEquals(2, queryResults.size());
        Integer assertionsConfirmed = 0;
        for(ProjectPaymentsController.ContactWrapper wrapper : queryResults){
            System.assertEquals(2, wrapper.contactRecord.Payments__r.size());
            assertionsConfirmed += 1;
        }
        System.assertEquals(2, assertionsConfirmed);

        queryResults = ProjectPaymentsController.getProjectPayments(project2.Id);

        // Check that the query results contain the number of records we're expecting
        System.assertEquals(2, queryResults.size());
        assertionsConfirmed = 0;
        for(ProjectPaymentsController.ContactWrapper wrapper : queryResults){
            System.assertEquals(2, wrapper.contactRecord.Payments__r.size());
            assertionsConfirmed += 1;
        }
        System.assertEquals(2, assertionsConfirmed);
        Test.stopTest();
    }

    @TestSetup
    static void makeData(){
        contact1 = new Contact(FirstName = 'Test', LastName = 'Person1');
        contact2 = new Contact(FirstName = 'Test', LastName = 'Person2');
        Database.insert(new List<Contact>{contact1, contact2});
    
        project1 = new Project__c(Name = 'Test Project1');
        project2 = new Project__c(Name = 'Test Project2');
        Database.insert(new List<Project__c>{project1, project2});
        
        payment11 = new Payment__c(Contact__c = contact1.Id, Project__c = project1.Id, Payment_Amount__c = 1000, Payment_Date__c = Date.today());
        payment12 = new Payment__c(Contact__c = contact1.Id, Project__c = project2.Id, Payment_Amount__c = 10000, Payment_Date__c = Date.today().addDays(-30));
        payment21 = new Payment__c(Contact__c = contact2.Id, Project__c = project1.Id, Payment_Amount__c = 123, Payment_Date__c = Date.today().addDays(-2));
        payment22 = new Payment__c(Contact__c = contact2.Id, Project__c = project2.Id, Payment_Amount__c = 2345, Payment_Date__c = Date.today().addDays(-31));
        Database.insert(new List<Payment__c>{payment11, payment12, payment21, payment22});
    }

    // Load project records that were created by TestSetup
    private static void loadProjects(){
        // Clearing out static record instances so this method can be re-called 
        // for checking results throughout unit tests
        project1 = null;
        project2 = null;
        for(Project__c project : [select Id, Name, Total_Payments__c from Project__c]){
            if(project.Name == 'Test Project1') project1 = project;
            else if(project.Name == 'Test Project2') project2 = project;
        }
    }
}