force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000}-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProjectUtils.cls
public class ProjectUtils {
    public static List<Project__c> calculatePaymentFields(Set<Id> projectIds){
        Map<Id, Project__c> calculatedProjects = new Map<Id, Project__c>();
        List<AggregateResult> AggregateContacts = [select Project__c, Sum(Payment_Amount__c) amount 
                                                    from Payment__c 
                                                    where Project__c in :projectIds 
                                                    group by Project__c];
        for(AggregateResult aggr : AggregateContacts){             
            Project__c calcProject = new Project__c(); 
            calcProject.Id = (Id)aggr.get('Project__c'); 
            calcProject.Total_Payments__c = (decimal)aggr.get('amount');
            calculatedProjects.put(calcProject.Id, calcProject);
        }
        
        // For any Projects that had their last payment deleted they won't 
        // show up in the aggregate results so we need to set their Total_Payments__c to null
        for(Id projectId : projectIds){
            if(!calculatedProjects.keySet().contains(projectId)){
                calculatedProjects.put(projectId, new Project__c(Id=projectId, Total_Payments__c=null));
            }
        }
        
        return calculatedProjects.values();
    }
}