force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{000}-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentUtils.cls
/**
* @author Charles Howard
* @date 2020
*
* @description Utility class for the Payment__c object that includes trigger handlers
* and utility functions for calculating things on related records
*/

public with sharing class PaymentUtils {
    /* Trigger Handlers */
    public static void handleBeforeInsert(){}
    public static void handleBeforeUpdate(){}
    public static void handleBeforeDelete(){}

    /**
    * @description
    */
    public static void handleAfterInsert(){
        // Collect the list of referenced Projects and Contacts that need to be recalculated
        Set<Id> projectsForRecalc = new Set<Id>();
        Set<Id> contactsForRecalc = new Set<Id>();
        for(Payment__c payment : (List<Payment__c>) Trigger.new)
        {
            projectsForRecalc.add(payment.Project__c);
            contactsForRecalc.add(payment.Contact__c);
        }

        // Make the call to recalculate and update related Project and Contacts
        updateRelatedRecords(projectsForRecalc, contactsForRecalc);
    }

    /**
    * @description
    */
    public static void handleAfterUpdate(){
        // For any updates to Project, Contact, Amount or Date
        // Collect the list of referenced Projects and Contacts that need to be recalculated
        Set<Id> projectsForRecalc = new Set<Id>();
        Set<Id> contactsForRecalc = new Set<Id>();
        for(Payment__c payment : (List<Payment__c>) Trigger.new)
        {
            // Compare the new version of the Payment to the old version and add Contacts
            // and Projects to Id Sets to update, based on the changes that were made
            Payment__c oldPayment = (Payment__c) Trigger.oldMap.get(payment.Id);
            // Project Change
            if(oldPayment.Project__c != payment.Project__c){
                projectsForRecalc.add(oldPayment.Project__c);
                projectsForRecalc.add(payment.Project__c);
            }
            // Contact Change
            if(oldPayment.Contact__c != payment.Contact__c){
                contactsForRecalc.add(oldPayment.Contact__c);
                contactsForRecalc.add(payment.Contact__c);
            }
            // Payment Amount Change
            if(oldPayment.Payment_Amount__c != payment.Payment_Amount__c){
                projectsForRecalc.add(payment.Project__c);
                contactsForRecalc.add(payment.Contact__c);
            }
            // Payment Date Change
            if(oldPayment.Payment_Date__C != payment.Payment_Date__C){
                contactsForRecalc.add(payment.Contact__c);
            }
        }

        // Make the call to recalculate and update related Project and Contacts
        updateRelatedRecords(projectsForRecalc, contactsForRecalc);
    }

    /**
    * @description
    */
    public static void handleAfterDelete(){
        // Collect the list of referenced Projects and Contacts that need to be recalculated
        Set<Id> projectsForRecalc = new Set<Id>();
        Set<Id> contactsForRecalc = new Set<Id>();
        for(Payment__c payment : (List<Payment__c>) Trigger.old)
        {
            projectsForRecalc.add(payment.Project__c);
            contactsForRecalc.add(payment.Contact__c);
        }

        // Make the call to recalculate and update related Project and Contacts
        updateRelatedRecords(projectsForRecalc, contactsForRecalc);
    }

    /**
    * @description
    */
    public static void handleAfterUndelete(){
        // Collect the list of referenced Projects and Contacts that need to be recalculated
        Set<Id> projectsForRecalc = new Set<Id>();
        Set<Id> contactsForRecalc = new Set<Id>();
        for(Payment__c payment : (List<Payment__c>) Trigger.new)
        {
            projectsForRecalc.add(payment.Project__c);
            contactsForRecalc.add(payment.Contact__c);
        }

        // Make the call to recalculate and update related Project and Contacts
        updateRelatedRecords(projectsForRecalc, contactsForRecalc);
    }

    /* Helper Methods */

    /**
    * @description 
    * @param projectsToRecalc
    * @param contactsToRecalc
    */
    private static void updateRelatedRecords(Set<Id> projectsToRecalc, Set<Id> contactsToRecalc){
        // Call helper methods to calculate Payment fields on related Projects and Contacts
        List<Project__c> projectsToUpdate = ProjectUtils.calculatePaymentFields(projectsToRecalc);
        List<Contact> contactsToUpdate = ContactUtils.calculatePaymentFields(contactsToRecalc);
        
        Database.update(projectsToUpdate);
        Database.update(contactsToUpdate);
        
    }
}